---
name: yaml-language-server-main
description: Language Server for YAML Files.
homepage: https://github.com/redhat-developer/yaml-language-server
licenses:
  - MIT
languages:
  - YAML
categories:
  - LSP

source:
  id: pkg:npm/yaml-language-server@1.13.1-7dd0fc7.0

bin:
  yaml-language-server: npm:yaml-language-server
